// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sayHello.proto

package grpc.example;

public interface HelloResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service.HelloResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>optional string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
